# Python CircleCI 2.0 configuration file
version: 2.1
orbs:
    node: circleci/node@1.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo and pulls code down from GitHub
      - checkout
      - run: echo "a first hello"
      - run: sleep 25
      - setup_remote_docker:
            docker_layer_caching: true
            version: 18.06.0-ce

      # Step 2: create virtual env and install dependencies
      # maybe use conda for this step instead?
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator
workflows:
version: 2
build-master:
  jobs:
    - build
    - publish-image:
        requires:
          - build
        filters:
          branches:
            only: master
